#!/bin/bash
# 4-GPU STORY QUEUE -- the controlled architecture factorial.
#
#   mkdir -p logs/story_queue
#   DRY_RUN=1 ./scripts/run_4gpu_story_queue.sh          # measure first
#   nohup ./scripts/run_4gpu_story_queue.sh > logs/story_queue/driver.log 2>&1 &
#
# Stop it with:  touch logs/story_queue/STOP   (or Ctrl-C / SIGTERM)
# Resume it with: just run it again. Completed stages are skipped via marker
# files in logs/story_queue/state/, and train.py auto-resumes an interrupted
# stage from its own latest checkpoint.
#
#
# WHY THIS QUEUE EXISTS
# =====================
# Every architecture number in private/results*.csv is confounded. The three
# 2500h lineages differ in THREE ways at once:
#
#     lineage                  encoder        l2a map            diversity
#     paperlr                  self-attn      weighted_average   --
#     fixednoam_conformer_k31  conformer k31  mlp                0.1
#     fixednoam_ebf            E-Branchformer mlp                0.1
#
# and they used different pretrain batch sizes (128 vs 96), hence different
# Noam values. So "MSDWild 18.31 -> 17.06" bundles the frame encoder, the
# latents2attractors map, the attractor objective AND the optimizer budget
# into a single number -- and `mlp` and the diversity loss have never once
# been run apart from each other.
#
# This queue runs five arms under ONE identical recipe, each differing from
# its comparison partner in exactly one factor. Configs are generated by
# scripts/gen_story_queue_configs.py, which is also where the design is
# documented; read its docstring before changing anything here.
#
#     arm  encoder        l2a map            Le    diversity   queued
#     A0   self_attention weighted_average   1.0   0.0         no
#     A1   conformer k31  weighted_average   1.0   0.0         YES
#     A2   self_attention weighted_average   0.0   0.1         YES
#     A3   self_attention mlp                0.0   0.1         YES
#     A4   conformer k31  mlp                0.0   0.1         YES  <- proposed
#
#     matched-recipe ablations (architecture-level attribution):
#       frame encoder        A3 -> A4   (attractor branch fixed = ours)
#       latents2attractors   A2 -> A3   (map alone)
#       attractor branch     A1 -> A4   (encoder fixed = conformer; the map
#                                        and the objective move together, so
#                                        this is the branch as a PACKAGE)
#       resolution matching  A4, per corpus (below)
#     system-level comparison:
#       A1 and A4 vs the published numbers, and vs paperlr (our faithful
#       reproduction of the published recipe)
#
#     A1 -> A4 and A2 -> A3 together decompose the attractor branch: the
#     package effect on a fixed encoder, and the map component on its own.
#
#
# THE BASELINE IS THE PUBLISHED METHOD, AS PUBLISHED
# ==================================================
# A0 and A1 are DEFINED (configs exist, so either can be re-enabled with one
# env var) but NOT QUEUED. That is a scope decision, not a gap.
#
# The baseline for this work is DiaPer as the authors specified it, and
# `paperlr` already reproduces that recipe faithfully -- including the
# authors' own finetune LR of 1e-6 -- scoring MSDWild 18.31 (ep 551-561) and
# RAMC 20.80 (ep 321-331). Re-finetuning that architecture at OUR recipe
# would mean improving the published baseline's optimizer settings. That is
# the authors' work, not ours; where their recipe underperforms, that is
# their published number to own.
#
# So: each method at its own recipe -- theirs as published, ours as ours,
# with the recipe counted as part of our system. Two claim levels, kept
# separate:
#
#   system level        A4 vs the published numbers and vs paperlr. The
#                       recipe is part of the system, so the gain is the
#                       system's.
#   architecture level  the matched-recipe ablations below, where the encoder
#                       and the attractor map are isolated with everything
#                       else identical.
#
# Any claim of the form "the conformer is worth X DER" comes from A3 -> A4,
# never from A4-vs-paperlr.
#
# The Le -> diversity swap has its matched-recipe evidence in the 300h sweep
# (two LR-clean isolated pairs: removing Le costs +0.77 MSDWild, adding
# unmasked diversity +0.36) -- see research_story.md. A1 is not queued
# because its only single-variable partner was A0.
#
#
# H4 -- RESOLUTION MATCHING, AND WHY IT IS A MECHANISM NOT A KNOB
# ==============================================================
# Each corpus keeps its OWN standard inference protocol; only *training*
# resolution varies. So the same intervention is the matched arm on one
# corpus and the mismatched arm on the other:
#
#   RAMC     infers at subsampling 5  -> train@5 is MATCHED    (expect a gain)
#            (train@10 is the default DiaPer recipe = mismatched)
#   MSDWild  infers at subsampling 10 -> train@5 is MISMATCHED (expect NO gain)
#
# The MSDWild null result is the point: it rules out "finer is just better".
# Both arms run on A4, which is a complete H4 test on one architecture: RAMC
# train@10 (mismatched) vs train@5 (matched), plus the MSDWild train@5 null.
#
#
# THE PROTOCOL (identical in every finetune)
# ==========================================
#   lr 1e-5, max_epochs 500, early stopping OFF, last-10-checkpoint average
#   scored ONCE at the cap. MSDWild dev has ZERO speaker-count overlap with
#   its test set (dev 97.2% five-to-ten speakers, test 100% two-to-four), so
#   no dev-based selector is valid and the cap must be a prior commitment.
#   Batch 64 for sub10/600-frame arms, 32 for sub5/1200-frame arms so that
#   tokens-per-batch match across resolutions and H4 compares resolution and
#   nothing else.
#
#
# LANES (one arm per GPU, no DDP)
# ===============================
# Per-arm DDP would cut wall-clock but splits each rank's loader, which is
# exactly the bookkeeping error that left a 2x-wrong chunk count sitting in
# every config header in this repo for weeks. Not reintroducing it.
#
#   A (gpu0)  A4: pretrain -> adapt -> MSDWild -> MSDWild@sub5     ~89 h
#   B (gpu1)  A2: pretrain -> adapt -> MSDWild, then A4 RAMC@sub5  ~96 h
#   C (gpu2)  A3: pretrain -> adapt -> MSDWild, then A4 RAMC@sub10 ~76 h
#   D (gpu3)  A1: pretrain -> adapt -> MSDWild                     ~63 h
#
# A4's two RAMC finetunes ride on lanes B and C rather than queueing behind
# A4's own MSDWild work: that keeps the critical path at ~96 h instead of
# ~135 h. A4's adapt finishes near 50 h while B and C need ~63 h for their
# own arms, so their wait_for_stage A4_adapt calls are correctness guards
# rather than real stalls.
#
#
# ENV KNOBS
# =========
#   DRY_RUN=1              probe every stage (VRAM + steps/epoch + sec/step)
#                          and exit without training anything
#   PROBE_STEPS            optimizer steps per probed stage (default 30) --
#                          this is what bounds the dry run
#   PROBE_TIMEOUT          backstop seconds per stage (default 900) for a
#                          stage that never reaches a step at all
#   PROBE_REPORT_EVERY     train.py --log-report-batches-num during the
#                          probe (default 1), i.e. step-counting resolution
#   PROBE_POLL             seconds between log checks (default 0.2). This
#                          bounds how far past PROBE_STEPS a stage overshoots
#   PROBE_VRAM_EVERY       sample nvidia-smi once per N log polls (default
#                          10); nvidia-smi is ~100 ms+, the log check is not
#   PROBE_BATCHES          sweep train_batchsize during a dry run, e.g.
#                          "16,20,24" -- one reported row per batch. Sweep on
#                          the heaviest arm (STORY_ARMS=A4) and apply the
#                          answer to all arms; see the note at its assignment
#   ONLY_LANE=A,C          restrict to these lanes
#   STORY_ARMS             which arms to run (default "A2 A3 A4"). A0/A1 are
#                          defined but out of scope -- see "THE BASELINE IS
#                          THE PUBLISHED METHOD" above before enabling them
#   LANE_{A,B,C,D}_GPU     physical GPU per lane (default 0,1,2,3)
#   LOG_DIR                default logs/story_queue
#   EXP_ROOT, DIAPER_ENV, DSCORE_SRC, DSCORE_ENV, USE_CONDA_RUN
#   MAX_CHECKPOINTS_TO_AVERAGE   default 10

set -u

LANE_A_GPU="${LANE_A_GPU:-0}"
LANE_B_GPU="${LANE_B_GPU:-1}"
LANE_C_GPU="${LANE_C_GPU:-2}"
LANE_D_GPU="${LANE_D_GPU:-3}"
ONLY_LANE="${ONLY_LANE:-}"
# Which arms to run. A0 and A1 are DEFINED (configs exist) but NOT queued by
# default -- see "THE BASELINE IS THE PUBLISHED METHOD" above.
STORY_ARMS="${STORY_ARMS:-A1 A2 A3 A4}"
DRY_RUN="${DRY_RUN:-0}"
# The dry run is bounded by STEPS, not wall clock: a fixed number of seconds
# gives a slow stage only a couple of steps while wasting time on a fast one.
PROBE_STEPS="${PROBE_STEPS:-30}"
# Report every batch so the poll loop can see the exact step it must stop on.
PROBE_REPORT_EVERY="${PROBE_REPORT_EVERY:-1}"
# How often to re-read the training log, in seconds. This bounds how far past
# PROBE_STEPS a stage can overshoot, so keep it small -- it is only a grep on
# a small file. VRAM is sampled once every PROBE_VRAM_EVERY polls instead,
# because nvidia-smi costs ~100 ms+ and pairing the two made the loop blind
# to progress for ~2 s at a time (long enough for tens of steps to pass).
PROBE_POLL="${PROBE_POLL:-0.2}"
PROBE_VRAM_EVERY="${PROBE_VRAM_EVERY:-10}"
# Comma-separated batch sizes to sweep during a dry run, e.g. "16,20,24".
# Empty = probe once at each config's own train_batchsize. Use this to find
# the largest batch that fits instead of extrapolating from OOM/no-OOM: the
# fixed-vs-per-item memory split is not what linear guessing predicts.
#
# Sweep on the HEAVIEST arm only (STORY_ARMS=A4) and apply the answer to
# every arm. The batch has to be identical across arms within a stage or
# A2->A3 (map) and A3->A4 (encoder) are confounded by batch and step count,
# which defeats the point of the queue. The lighter self-attention arms
# therefore sit below the ceiling by design; that is the cost of the control,
# not wasted capacity.
PROBE_BATCHES="${PROBE_BATCHES:-}"
# Safety backstop only -- fires if a stage cannot reach PROBE_STEPS at all
# (bad cache, OOM, a hung loader). PROBE_SECONDS is honoured as an alias.
PROBE_TIMEOUT="${PROBE_TIMEOUT:-${PROBE_SECONDS:-900}}"
LOG_DIR="${LOG_DIR:-logs/story_queue}"

DIAPER_ENV="${DIAPER_ENV:-/data/ocr/namvt17/custom-diaper/.venv}"
DSCORE_SRC="${DSCORE_SRC:-/data/ocr/namvt17/custom-diaper/dscore}"
DSCORE_ENV="${DSCORE_ENV:-/data/ocr/namvt17/custom-diaper/dscore/.dscore}"
EXP_ROOT="${EXP_ROOT:-/data/ocr/namvt17/custom-diaper/experiments/10attractors}"
MAX_CHECKPOINTS_TO_AVERAGE="${MAX_CHECKPOINTS_TO_AVERAGE:-10}"

CFG_ROOT=models/10attractors
STATE_DIR="$LOG_DIR/state"
DRY_DIR="$LOG_DIR/dryrun"
STOP_FILE="$LOG_DIR/STOP"
# Cross-lane mutex. Whole-recording RAMC inference is CPU-only and takes
# ~120-130 GB RAM; two concurrent runs (~250 GB) take the box down, so they
# must serialize. See memory diaper-ramc-infer-hardware-limit.
RAMC_LOCK="$LOG_DIR/ramc_infer.lock"

mkdir -p "$LOG_DIR" "$STATE_DIR"

if [ "${USE_CONDA_RUN:-1}" = "1" ]; then
    PY=(conda run -p "$DIAPER_ENV" --no-capture-output python)
    DSCORE_PY=(conda run -p "$DSCORE_ENV" --no-capture-output python -u)
else
    PY=(python)
    DSCORE_PY=(python -u)
fi

log ()            { echo "[$(date '+%Y-%m-%d %H:%M:%S')] $*"; }
yaml_get ()       { grep "^$1:" "$2" | head -1 | sed "s|^$1: *||"; }
stop_requested () { [ -f "$STOP_FILE" ]; }
stage_done ()     { [ -f "$STATE_DIR/$1.done" ]; }
mark_stage ()     { touch "$STATE_DIR/$1.done"; }
lane_enabled () {
    [ -z "$ONLY_LANE" ] && return 0
    case ",$ONLY_LANE," in *",$1,"*) return 0;; esac
    return 1
}
arm_queued () { case " $STORY_ARMS " in *" $1 "*) return 0;; esac; return 1; }

# wait_for_stage <key> -- block until another lane marks <key> done. Lane D's
# A4 RAMC finetunes need A4's adapt checkpoint, which lane A produces; waiting
# here instead of chaining them onto lane A cuts the critical path from ~135 h
# to ~96 h. Returns non-zero if STOP is requested.
wait_for_stage () {
    local key="$1" waited=0
    while ! stage_done "$key"; do
        if stop_requested; then
            log "  STOP requested while waiting for $key"; return 1
        fi
        if [ $((waited % 1800)) -eq 0 ]; then
            log "  waiting for $key (${waited}s elapsed)"
        fi
        sleep 60; waited=$((waited + 60))
    done
    return 0
}

# A background lane subshell ignores a bare SIGINT, so tear down the whole
# process group -- same escalation as run_36h_resume_queue.sh.
on_signal () {
    trap - INT TERM
    log "caught SIG$1 -- stopping the queue"
    : > "$STOP_FILE"
    local mypgid
    mypgid=$(ps -o pgid= -p $$ 2>/dev/null | tr -d ' ')
    if [ -n "$mypgid" ] && [ "$mypgid" = "$$" ]; then
        kill -TERM 0 2>/dev/null; sleep 5; kill -KILL 0 2>/dev/null
    else
        pkill -TERM -P $$ 2>/dev/null
    fi
    exit 130
}
trap 'on_signal INT' INT
trap 'on_signal TERM' TERM

ramc_lock_acquire () {
    local label="$1" waited=0
    while ! mkdir "$RAMC_LOCK" 2>/dev/null; do
        if stop_requested; then return 1; fi
        if [ $((waited % 600)) -eq 0 ]; then
            log "  $label waiting for the RAMC inference lock (${waited}s)"
        fi
        sleep 30; waited=$((waited + 30))
    done
    echo "$label $$" > "$RAMC_LOCK/owner"
    return 0
}
ramc_lock_release () { rm -rf "$RAMC_LOCK"; }

# ---------------------------------------------------------------------------
# train_stage <key> <gpu> <cfg>
#
# Each arm owns its output_path, so no --output-path override is needed and
# there is no risk of writing into another run's directory.
#
# THE init_model_path TRAP (memory diaper-36h-resume-queue): train.py runs
#   if args.init_model_path != '': average_checkpoints(...)
# UNCONDITIONALLY, before it ever checks output_path for a resumable
# checkpoint. So an interrupted-and-restarted stage first tries to load its
# configured init weights and only overwrites that model moments later. If
# those init weights are absent the stage crashes on startup even though the
# resume never needed them. When a real resume checkpoint exists we pass
# --init-model-path '' (empty satisfies the != '' gate and skips the
# averaging entirely -- harmless, the resume would discard its result).
# ---------------------------------------------------------------------------
train_stage () {
    local key="$1" gpu="$2" cfg="$3"
    if stage_done "$key"; then log "SKIP  $key (already done)"; return 0; fi
    if stop_requested; then log "STOP requested -- not starting $key"; return 1; fi
    if [ ! -f "$cfg" ]; then log "FATAL $key -- no config $cfg"; return 1; fi

    local out logfile init_args=()
    out="$(yaml_get output_path "$cfg")"
    logfile="$LOG_DIR/$key.log"

    local n_resume
    n_resume=$(find "$out/models" -maxdepth 1 -name 'checkpoint_*.tar' \
               2>/dev/null | wc -l)
    if [ "$n_resume" -gt 0 ]; then
        local last
        last=$(find "$out/models" -maxdepth 1 -name 'checkpoint_*.tar' \
               -exec basename {} \; \
               | sed -E 's/checkpoint_([0-9]+)\.tar/\1/' | sort -n | tail -1)
        log "START $key gpu=$gpu (RESUMING from epoch $last, skipping warm start)"
        init_args=(--init-model-path '')
    else
        local init_path
        init_path="$(yaml_get init_model_path "$cfg")"
        if [ -n "$init_path" ]; then
            local n_init
            n_init=$(find "$init_path" -maxdepth 1 -name 'checkpoint_*.tar' \
                     2>/dev/null | wc -l)
            if [ "$n_init" -eq 0 ]; then
                log "FATAL $key -- init weights missing at $init_path"
                log "      Refusing: this would train from random init and"
                log "      silently answer a different question."
                return 1
            fi
            log "START $key gpu=$gpu (fresh, warm start from $n_init ckpt at $init_path)"
        else
            log "START $key gpu=$gpu (fresh, from random init -- pretrain stage)"
        fi
    fi

    env CUDA_VISIBLE_DEVICES="$gpu" "${PY[@]}" diaper/train.py -c "$cfg" \
        --gpu 1 "${init_args[@]+"${init_args[@]}"}" >> "$logfile" 2>&1
    local rc=$?
    if [ $rc -eq 0 ]; then log "DONE  $key"; mark_stage "$key"; return 0; fi
    log "FAIL  $key (exit $rc) -- see $logfile"
    stop_requested && return 1
    log "RETRY $key once (train.py resumes from its own checkpoints)"
    env CUDA_VISIBLE_DEVICES="$gpu" "${PY[@]}" diaper/train.py -c "$cfg" \
        --gpu 1 --init-model-path '' >> "$logfile" 2>&1
    rc=$?
    if [ $rc -eq 0 ]; then
        log "DONE  $key (after retry)"; mark_stage "$key"; return 0
    fi
    log "FAIL  $key (exit $rc, after retry)"; return 1
}

# ---------------------------------------------------------------------------
# score_stage <key> <gpu> <infer_cfg> <corpus>
#
# corpus=msdwild: GPU, subsampling 10 / median 11, dscore --collar 0.25
# corpus=ramc:    CPU ONLY (--gpu 0, ~120-130 GB RAM), subsampling 5 /
#                 median 1, dscore at collar 0 (its default, no flag), and
#                 takes the cross-lane lock.
#
# The dscore log filename EMBEDS THE EPOCH RANGE deliberately: an earlier
# queue wrote a fixed filename every call, and once a later round added more
# rttms nobody could tell which epochs a score belonged to -- all nine stages
# had to be rescored by hand. Do not "simplify" this away.
# ---------------------------------------------------------------------------
score_stage () {
    local key="$1" gpu="$2" cfg="$3" corpus="$4"
    if stage_done "$key"; then log "SKIP  $key (already done)"; return 0; fi
    if stop_requested; then log "STOP requested -- not scoring $key"; return 1; fi
    if [ ! -f "$cfg" ]; then log "FATAL $key -- no config $cfg"; return 1; fi

    local models_path rttms_dir logfile median subs collar_args=()
    models_path="$(yaml_get models_path "$cfg")"
    rttms_dir="$(yaml_get rttms_dir "$cfg")"
    logfile="$LOG_DIR/$key.log"
    if [ "$corpus" = "msdwild" ]; then
        median=11; subs=10; collar_args=(--collar 0.25)
    else
        median=1;  subs=5
    fi

    if [ ! -d "$models_path" ]; then
        log "SKIP  $key -- no models dir $models_path"; return 1
    fi
    mapfile -t ck < <(find "$models_path" -maxdepth 1 -name 'checkpoint_*.tar' \
        -exec basename {} \; | sed -E 's/checkpoint_([0-9]+)\.tar/\1/' | sort -n)
    if [ "${#ck[@]}" -eq 0 ]; then
        log "SKIP  $key -- no checkpoints in $models_path"; return 1
    fi
    local li=$(( ${#ck[@]} - 1 )) si
    si=$(( ${#ck[@]} > MAX_CHECKPOINTS_TO_AVERAGE \
           ? ${#ck[@]} - MAX_CHECKPOINTS_TO_AVERAGE : 0 ))
    local range="$(( ${ck[$si]} - 1 ))-${ck[$li]}"

    local infer_gpu=1
    if [ "$corpus" = "ramc" ]; then
        infer_gpu=0
        ramc_lock_acquire "$key" || return 1
    fi

    log "START $key epochs=$range (corpus=$corpus, subsampling=$subs, median=$median)"
    env CUDA_VISIBLE_DEVICES="$gpu" "${PY[@]}" diaper/infer.py -c "$cfg" \
        --models-path "$models_path" --rttms-dir "$rttms_dir" \
        --epochs "$range" --median-window-length "$median" \
        --subsampling "$subs" --gpu "$infer_gpu" --num-threads 4 \
        >> "$logfile" 2>&1
    local rc=$?
    [ "$corpus" = "ramc" ] && ramc_lock_release
    if [ $rc -ne 0 ]; then log "FAIL  $key infer (exit $rc) -- see $logfile"; return 1; fi

    mapfile -t sys_rttms < <(find "$rttms_dir/epochs${range}" \
        -path "*/median${median}/*/rttms/*.rttm" -type f 2>/dev/null)
    if [ "${#sys_rttms[@]}" -eq 0 ]; then
        log "WARN  $key -- no RTTMs under $rttms_dir/epochs${range}"; return 1
    fi

    local infer_data_dir ref_rttm score_log collar_tag
    infer_data_dir="$(yaml_get infer_data_dir "$cfg")"
    ref_rttm="${infer_data_dir}/rttm"
    collar_tag=$([ "$corpus" = "msdwild" ] && echo "0.25" || echo "0")
    score_log="${rttms_dir}/dscore_collar${collar_tag}_epochs${range}.log"
    "${DSCORE_PY[@]}" "$DSCORE_SRC/score.py" \
        "${collar_args[@]+"${collar_args[@]}"}" \
        -r "$ref_rttm" -s "${sys_rttms[@]}" > "$score_log" 2>&1
    log "SCORED $key (${#sys_rttms[@]} files) -> $score_log"
    grep -h "OVERALL" "$score_log" || log "WARN  no OVERALL line in $score_log"
    mark_stage "$key"
    return 0
}

# ---------------------------------------------------------------------------
# probe_stage <key> <gpu> <cfg>   (DRY_RUN only)
#
# Runs the stage for PROBE_STEPS optimizer steps (not a fixed wall clock)
# into a THROWAWAY output_path and reports:
#   peak VRAM        -- does batch 64 actually fit in 32 GB?
#   steps/epoch      -- read straight off train.py's "batch i/TOTAL" report,
#                       which also finally settles the never-counted 2500h
#                       pretrain cache: chunks = steps/epoch * batch
#   startup          -- launch -> first observed step. This, not the steps,
#                       is what dominates a probed stage's wall clock (torch
#                       import, opening the precomputed cache, model build)
#   sec/step         -- measured across observed steps, startup excluded
#   est. stage hours -- sec/step * steps/epoch * max_epochs
#   realised ramp %  -- noam_warmup_steps / (steps/epoch * max_epochs), for
#                       the SC stages, so the write-up can state it correctly
#   why it stopped   -- "30 steps" normally, or TIMEOUT/exited early
#
# PROBE_TIMEOUT is only a backstop for a stage that never reaches a step.
# An OOM is detected and named explicitly, since that is the whole point of
# probing before committing ~324 GPU-h.
#
# --init-model-path '' is forced: a dry run has to work BEFORE anything has
# trained, so warm-start weights generally do not exist yet. VRAM and
# throughput are unaffected by which weights are loaded.
# ---------------------------------------------------------------------------
probe_stage () {
    local key="$1" gpu="$2" cfg="$3" batch_override="${4:-}"
    if [ ! -f "$cfg" ]; then
        printf '  %-34s CONFIG MISSING (%s)\n' "$key" "$cfg"; return 1
    fi
    local batch epochs warmup subs frames plog vram_file samples out
    batch="$(yaml_get train_batchsize "$cfg")"
    if [ -n "$batch_override" ]; then
        batch="$batch_override"
        key="${key}_b${batch}"
    fi
    epochs="$(yaml_get max_epochs "$cfg")"
    warmup="$(yaml_get noam_warmup_steps "$cfg")"
    subs="$(yaml_get subsampling "$cfg")"
    frames="$(yaml_get num_frames "$cfg")"
    out="$DRY_DIR/$key"
    plog="$LOG_DIR/dryrun_$key.log"
    vram_file="$DRY_DIR/$key.vram"
    samples="$DRY_DIR/$key.samples"
    mkdir -p "$out"
    : > "$plog"; : > "$vram_file"; : > "$samples"

    # train.py writes straight to $plog -- no awk timestamper, because the
    # poll loop below already knows the clock, and avoiding the pipeline
    # leaves a single child to tear down instead of three.
    # The subshell writes an exit-code sentinel when the child is really
    # done. `kill -0` is not usable for this: it SUCCEEDS on a zombie child,
    # so a stage that dies at startup would otherwise sit out the whole
    # backstop timeout instead of being reported immediately.
    local rcfile="$DRY_DIR/$key.rc"
    rm -f "$rcfile"
    # Three things matter in this launch, all learned the hard way:
    #  - the subshell's OWN fds go to $plog, never inherited. Otherwise, when
    #    probe_stage is called inside a command substitution, the background
    #    job holds that pipe open and the substitution blocks until the job
    #    dies -- which looks exactly like a hang.
    #  - `set -m` puts the job in its own process group, so the teardown can
    #    kill env/conda/python together with one signal. Killing $! alone
    #    only reaps the subshell and orphans the grandchild.
    #  - `timeout` is a belt-and-braces backstop so the child cannot outlive
    #    the probe even if the group kill fails.
    set -m
    ( timeout --signal=KILL "$PROBE_TIMEOUT" \
          env CUDA_VISIBLE_DEVICES="$gpu" "${PY[@]}" diaper/train.py -c "$cfg" \
          --gpu 1 --output-path "$out" --init-model-path '' \
          --train-batchsize "$batch" \
          --log-report-batches-num "$PROBE_REPORT_EVERY" --num-workers 2 \
          > "$plog" 2>&1; echo $? > "$rcfile" ) >>"$plog" 2>&1 &
    local runner=$!
    set +m

    # Poll: sample VRAM, and record (wall clock, batch index) pairs so
    # sec/step is measured over real steps with process startup excluded.
    # STEPS, not seconds, is the control: a fixed wall clock gives a slow
    # stage (adapt, 2400 frames) only a couple of steps while wasting time
    # on a fast one, and peak VRAM settles within a few steps anyway.
    # waited is real elapsed time, not accumulated sleeps -- each iteration
    # also pays for an nvidia-smi call, so counting sleeps alone understates
    # the wall clock and makes the backstop fire far later than configured.
    # The log is polled ~10x more often than VRAM is sampled. Checking the
    # log is a grep on a small file; nvidia-smi costs ~100 ms+, so pairing
    # them meant the loop could only notice progress every ~2 s -- long
    # enough for tens of steps to slip past PROBE_STEPS before it looked.
    # startup (launch -> first observed step) is reported separately, since
    # it, not the steps, is what dominates a stage's wall clock.
    local t0 waited=0 last_batch=0 stop_reason="" startup="" vram_due=0
    t0=$(date +%s)
    while : ; do
        if [ -f "$rcfile" ]; then
            stop_reason="exited on its own (rc=$(cat "$rcfile" 2>/dev/null))"
            break
        fi
        if [ "$vram_due" -le 0 ]; then
            nvidia-smi --query-gpu=memory.used --format=csv,noheader,nounits \
                -i "$gpu" >> "$vram_file" 2>/dev/null
            vram_due="$PROBE_VRAM_EVERY"
        fi
        vram_due=$(( vram_due - 1 ))
        last_batch=$(grep -oE 'batch [0-9]+/' "$plog" 2>/dev/null \
                     | tail -1 | grep -oE '^[0-9]+|[0-9]+' | tail -1 || true)
        last_batch="${last_batch:-0}"
        if [ "$last_batch" -gt 0 ]; then
            echo "$(date +%s) $last_batch" >> "$samples"
            [ -z "$startup" ] && startup=$(( $(date +%s) - t0 ))
        fi
        if [ "$last_batch" -ge "$PROBE_STEPS" ]; then
            stop_reason="$last_batch steps"
            break
        fi
        waited=$(( $(date +%s) - t0 ))
        if [ "$waited" -ge "$PROBE_TIMEOUT" ]; then
            stop_reason="TIMEOUT ${PROBE_TIMEOUT}s at step $last_batch"
            break
        fi
        sleep "$PROBE_POLL"
    done

    # Tear down. conda run spawns python as a grandchild, so killing the
    # runner alone can orphan a process still holding the GPU -- which would
    # corrupt the NEXT stage's VRAM reading. --output-path is unique per
    # stage, so it is a precise matcher for the straggler.
    #
    # Kill the whole process group (negative PID), which `set -m` above made
    # possible -- that gets env/conda/python in one shot without needing
    # pkill, which is absent on some dev machines. pkill is a guarded
    # fallback only, and can never be what hangs the probe.
    kill -KILL -- "-$runner" 2>/dev/null || kill -KILL "$runner" 2>/dev/null
    wait "$runner" 2>/dev/null
    if command -v pkill >/dev/null 2>&1; then
        timeout 10 pkill -KILL -f -- "--output-path $out" 2>/dev/null
    fi
    # Let the driver release the GPU before the next stage samples VRAM.
    sleep 3

    local peak steps_per_epoch secs_per_step
    peak=$(sort -n "$vram_file" 2>/dev/null | tail -1)
    steps_per_epoch=$(grep -oE 'batch [0-9]+/[0-9]+' "$plog" 2>/dev/null \
                      | head -1 | sed -E 's|.*/||')
    secs_per_step=$("${PY[@]}" - "$samples" <<'PYEOF' 2>/dev/null
import sys
pts = []
for line in open(sys.argv[1], encoding='utf-8', errors='replace'):
    parts = line.split()
    if len(parts) == 2:
        try:
            pts.append((int(parts[0]), int(parts[1])))
        except ValueError:
            pass
# Only samples where a step had already been reported, so the process
# startup cost (imports, model build, loader spin-up) is excluded.
pts = [p for p in pts if p[1] > 0]
if len(pts) >= 2 and pts[-1][1] > pts[0][1]:
    print(f'{(pts[-1][0] - pts[0][0]) / (pts[-1][1] - pts[0][1]):.3f}')
PYEOF
)
    if [ -z "${steps_per_epoch:-}" ]; then
        local why="no training step in ${waited}s"
        if grep -qiE 'out of memory|CUDA error' "$plog" 2>/dev/null; then
            why="OUT OF MEMORY -- lower this stage's train_batchsize"
        fi
        printf '  %-34s FAILED: %s (see %s)\n' "$key" "$why" "$plog"
        return 1
    fi
    local total_steps est_h ramp chunks
    total_steps=$(( steps_per_epoch * epochs ))
    chunks=$(( steps_per_epoch * batch ))
    if [ -n "${secs_per_step:-}" ]; then
        est_h=$("${PY[@]}" -c "print(f'{$secs_per_step*$total_steps/3600:.1f}')" \
                2>/dev/null)
    else
        est_h='?'
    fi
    if [ -n "$warmup" ]; then
        ramp=$("${PY[@]}" -c "print(f'{100*$warmup/$total_steps:.1f}%')" 2>/dev/null)
    else
        ramp='n/a'
    fi
    printf '  %-34s vram=%6s MiB  batch=%-3s frames=%-5s sub=%-2s steps/ep=%-6s chunks=%-7s startup=%-5s sec/step=%-6s est=%6sh  ramp=%-6s [%s]\n' \
        "$key" "${peak:-?}" "$batch" "$frames" "$subs" \
        "$steps_per_epoch" "$chunks" "${startup:-?}s" \
        "${secs_per_step:-?}" "$est_h" "$ramp" "$stop_reason"
    return 0
}

# ===========================================================================
# Stage definitions
# ===========================================================================
arm_dir () { echo "$CFG_ROOT/SC_LibriSpeech_2spk_2500h_story_$1"; }

# sc_stages <arm> -- pretrain then adapt. A0 has none (it inherits paperlr).
run_sc () {
    local arm="$1" gpu="$2" d
    d="$(arm_dir "$arm")"
    [ "$arm" = "A0" ] && { log "A0 inherits paperlr's SC stages -- nothing to train"; return 0; }
    train_stage "${arm}_pretrain" "$gpu" "$d/train.yaml"       || return 1
    train_stage "${arm}_adapt"    "$gpu" "$d/train_10spks.yaml" || return 1
    return 0
}

run_msdwild () {          # the H1/H2/H3 ablation benchmark
    local arm="$1" gpu="$2" d
    d="$(arm_dir "$arm")"
    train_stage "${arm}_ft_msdwild" "$gpu" "$d/finetune_msdwild_10spks.yaml" || return 1
    score_stage "${arm}_score_msdwild" "$gpu" "$d/infer_msdwild.yaml" msdwild
}

run_msdwild_sub5 () {     # H4 MISMATCHED arm -- expect no gain
    local arm="$1" gpu="$2" d
    d="$(arm_dir "$arm")"
    train_stage "${arm}_ft_msdwild_sub5" "$gpu" \
        "$d/finetune_msdwild_10spks_sub5.yaml" || return 1
    score_stage "${arm}_score_msdwild_sub5" "$gpu" \
        "$d/infer_msdwild_sub5trained.yaml" msdwild
}

run_ramc_sub10 () {       # H4 MISMATCHED arm (the default DiaPer recipe)
    local arm="$1" gpu="$2" d
    d="$(arm_dir "$arm")"
    train_stage "${arm}_ft_ramc" "$gpu" "$d/finetune_ramc_10spks.yaml" || return 1
    score_stage "${arm}_score_ramc" "$gpu" "$d/infer_ramc.yaml" ramc
}

run_ramc_sub5 () {        # H4 MATCHED arm
    local arm="$1" gpu="$2" d
    d="$(arm_dir "$arm")"
    train_stage "${arm}_ft_ramc_sub5" "$gpu" \
        "$d/finetune_ramc_10spks_sub5.yaml" || return 1
    score_stage "${arm}_score_ramc_sub5" "$gpu" \
        "$d/infer_ramc_sub5trained.yaml" ramc
}

# One arm per lane, and A4's two RAMC finetunes tacked onto lanes B and C
# once their own arm is done. A4's adapt lands around 50 h while B and C need
# ~63 h for their own arms, so the wait_for_stage calls below never actually
# stall -- they are correctness guards, not scheduling.
#
# Lane A: the proposed system, MSDWild side (its RAMC side is on B and C).
lane_A () {
    arm_queued A4 || { log "lane A: A4 not in STORY_ARMS -- nothing to do"; return 0; }
    run_sc A4 "$LANE_A_GPU" || return 1
    run_msdwild A4 "$LANE_A_GPU" || return 1
    run_msdwild_sub5 A4 "$LANE_A_GPU"
}

# Lane B: A2, then A4's RAMC matched arm (the expensive one, 33 h).
lane_B () {
    if arm_queued A0; then run_msdwild A0 "$LANE_B_GPU"; fi
    if arm_queued A2; then
        run_sc A2 "$LANE_B_GPU" || return 1
        run_msdwild A2 "$LANE_B_GPU" || return 1
    fi
    arm_queued A4 || return 0
    wait_for_stage A4_adapt || return 1
    run_ramc_sub5 A4 "$LANE_B_GPU"
}

# Lane C: A3, then A4's RAMC mismatched arm (the cheap one, 13 h).
lane_C () {
    if arm_queued A3; then
        run_sc A3 "$LANE_C_GPU" || return 1
        run_msdwild A3 "$LANE_C_GPU" || return 1
    fi
    arm_queued A4 || return 0
    wait_for_stage A4_adapt || return 1
    run_ramc_sub10 A4 "$LANE_C_GPU"
}

# Lane D: A1 -- the conformer encoder on the PAPER's attractor branch. Pairs
# with A4 (same encoder, our branch) for the attractor-branch package test,
# and stands on its own as a system-level row.
lane_D () {
    arm_queued A1 || { log "lane D: A1 not in STORY_ARMS -- nothing to do"; return 0; }
    run_sc A1 "$LANE_D_GPU" || return 1
    run_msdwild A1 "$LANE_D_GPU"
}

# ===========================================================================
# Preflight
# ===========================================================================
preflight () {
    local fail=0 d
    log "PREFLIGHT"

    log "  arms queued: $STORY_ARMS"
    for arm in $STORY_ARMS; do
        d="$(arm_dir "$arm")"
        if [ ! -d "$d" ]; then
            log "  FATAL $arm -- $d missing. Run:"
            log "        python scripts/gen_story_queue_configs.py"
            fail=1; continue
        fi
        log "  ok $arm configs at $d"
    done
    [ $fail -eq 1 ] && return 1

    if arm_queued A0; then
        # A0's whole point is that paperlr's adapt checkpoints already exist.
        local plr_adapt n
        plr_adapt="$(yaml_get init_model_path \
                     "$(arm_dir A0)/finetune_msdwild_10spks.yaml")"
        n=$(find "$plr_adapt" -maxdepth 1 -name 'checkpoint_*.tar' 2>/dev/null | wc -l)
        if [ "$n" -eq 0 ]; then
            log "  FATAL A0 -- paperlr adapt checkpoints missing at:"
            log "        $plr_adapt"
            log "        A0 inherits them; without them it would train from"
            log "        random init. Upload them with"
            log "        scripts/pack_weights_for_story_queue.sh."
            fail=1
        else
            log "  ok A0 inherits $n paperlr adapt checkpoint(s)"
        fi
    else
        log "  note A0 not queued by design -- the baseline is the published"
        log "       method as published (paperlr: MSDWild 18.31, RAMC 20.80)."
        log "       Architecture attribution comes from the matched-recipe"
        log "       ablations A2->A3 (map), A3->A4 (encoder) and A1->A4"
        log "       (attractor branch as a package, encoder fixed)."
    fi

    # Every precomputed cache and reference RTTM any queued arm reads. Uses
    # whichever queued arm carries the most config types as the reference.
    local ref_arm
    if arm_queued A4; then ref_arm=A4; else ref_arm="${STORY_ARMS%% *}"; fi
    local seen="" d_ref
    d_ref="$(arm_dir "$ref_arm")"
    for cfg in "$d_ref"/train.yaml "$d_ref"/train_10spks.yaml \
               "$d_ref"/finetune_msdwild_10spks.yaml \
               "$d_ref"/finetune_ramc_10spks.yaml; do
        [ -f "$cfg" ] || continue
        for k in train_precomputed_dir valid_precomputed_dir; do
            local p; p="$(yaml_get "$k" "$cfg")"
            case " $seen " in *" $p "*) continue;; esac
            seen="$seen $p"
            if [ -d "$p" ]; then
                log "  ok cache $p"
            else
                log "  FATAL cache missing: $p"; fail=1
            fi
        done
    done
    for cfg in "$d_ref"/infer_msdwild.yaml "$d_ref"/infer_ramc.yaml; do
        [ -f "$cfg" ] || continue
        local p; p="$(yaml_get infer_data_dir "$cfg")"
        if [ -f "$p/rttm" ]; then log "  ok reference $p/rttm"
        else log "  FATAL reference rttm missing: $p/rttm"; fail=1; fi
    done

    # The SC caches have never been counted; the dry run reads the true
    # steps/epoch off train.py itself, which is strictly better than counting
    # files. Just say so here rather than guessing.
    log "  note the 2500h pretrain cache chunk count is UNVERIFIED (configs"
    log "       assume 119,160; the physical count for 2500h of 60s chunks is"
    log "       150,000). DRY_RUN=1 reports the true steps/epoch and the"
    log "       realised Noam ramp for every SC stage -- run it and record"
    log "       those numbers for the write-up. The schedule is deliberately"
    log "       NOT changed either way: uniformity across arms matters more"
    log "       here, and paperlr's schedule is the one with results behind it."

    [ $fail -eq 1 ] && { log "PREFLIGHT FAILED"; return 1; }
    log "PREFLIGHT OK"
    return 0
}

# ===========================================================================
# Main
# ===========================================================================
# Standard "am I being sourced" idiom, so the helpers above can be sourced
# and exercised by a test without launching the queue. Used by
# scripts/test_story_queue.sh to verify the init_model_path trap handling.
(return 0 2>/dev/null) && return 0

if [ -n "${CUDA_VISIBLE_DEVICES:-}" ]; then
    IFS=',' read -r -a _cvd <<< "$CUDA_VISIBLE_DEVICES"
    LANE_A_GPU="${_cvd[0]:-$LANE_A_GPU}"
    LANE_B_GPU="${_cvd[1]:-$LANE_B_GPU}"
    LANE_C_GPU="${_cvd[2]:-$LANE_C_GPU}"
    LANE_D_GPU="${_cvd[3]:-$LANE_D_GPU}"
    log "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES -> lanes A/B/C/D on $LANE_A_GPU/$LANE_B_GPU/$LANE_C_GPU/$LANE_D_GPU"
    unset CUDA_VISIBLE_DEVICES
fi

rm -f "$STOP_FILE"
preflight || exit 1

if [ "$DRY_RUN" = "1" ]; then
    mkdir -p "$DRY_DIR"
    log "DRY RUN -- $PROBE_STEPS steps per stage (${PROBE_TIMEOUT}s backstop),"
    log "nothing real is trained."
    log "Stages run one at a time so the VRAM readings are not contaminated."
    echo
    [ -n "$PROBE_BATCHES" ] && \
        log "Sweeping train_batchsize over: $PROBE_BATCHES"
    # probe_one <key> <cfg> -- one row per swept batch, or one row at the
    # config's own batch when PROBE_BATCHES is empty.
    probe_one () {
        local pkey="$1" pcfg="$2" b
        if [ -z "$PROBE_BATCHES" ]; then
            probe_stage "$pkey" "$LANE_A_GPU" "$pcfg"
            return $?
        fi
        local oldifs="$IFS"; IFS=','
        for b in $PROBE_BATCHES; do
            IFS="$oldifs"
            probe_stage "$pkey" "$LANE_A_GPU" "$pcfg" "$b"
            IFS=','
        done
        IFS="$oldifs"
        return 0
    }

    for arm in $STORY_ARMS; do
        d="$(arm_dir "$arm")"
        echo "ARM $arm"
        [ "$arm" != "A0" ] && {
            probe_one "${arm}_pretrain" "$d/train.yaml"
            probe_one "${arm}_adapt"    "$d/train_10spks.yaml"
        }
        probe_one "${arm}_ft_msdwild" "$d/finetune_msdwild_10spks.yaml"
        [ -f "$d/finetune_msdwild_10spks_sub5.yaml" ] && \
            probe_one "${arm}_ft_msdwild_sub5" \
                "$d/finetune_msdwild_10spks_sub5.yaml"
        [ -f "$d/finetune_ramc_10spks.yaml" ] && \
            probe_one "${arm}_ft_ramc" "$d/finetune_ramc_10spks.yaml"
        [ -f "$d/finetune_ramc_10spks_sub5.yaml" ] && \
            probe_one "${arm}_ft_ramc_sub5" \
                "$d/finetune_ramc_10spks_sub5.yaml"
        echo
    done
    log "DRY RUN COMPLETE."
    log "Pick, per stage, the largest swept batch whose vram leaves ~2-3 GB of"
    log "headroom -- the probe never reaches the epoch-end dev pass, which"
    log "adds memory on top of what is reported here."
    log "Then set it in scripts/gen_story_queue_configs.py and regenerate;"
    log "do NOT edit the yaml by hand. For the pretrain and adapt stages the"
    log "Noam values must move WITH the batch (see that file's docstring) or"
    log "the LR schedule silently changes."
    log "Throwaway outputs are under $DRY_DIR (safe to delete)."
    exit 0
fi

log "STARTING story queue -- arms: $STORY_ARMS"
log "  lane A gpu $LANE_A_GPU: A4 pretrain->adapt->MSDWild->MSDWild@sub5"
log "  lane B gpu $LANE_B_GPU: A2 pretrain->adapt->MSDWild, then A4 RAMC@sub5"
log "  lane C gpu $LANE_C_GPU: A3 pretrain->adapt->MSDWild, then A4 RAMC@sub10"
log "  lane D gpu $LANE_D_GPU: A1 pretrain->adapt->MSDWild"

pids=()
for lane in A B C D; do
    if lane_enabled "$lane"; then
        ( "lane_$lane" ) > "$LOG_DIR/lane_$lane.log" 2>&1 &
        pids+=($!)
        log "  launched lane $lane (pid ${pids[-1]}) -> $LOG_DIR/lane_$lane.log"
    else
        log "  lane $lane disabled by ONLY_LANE=$ONLY_LANE"
    fi
done

rc=0
for p in "${pids[@]+"${pids[@]}"}"; do
    wait "$p" || rc=1
done

log "QUEUE FINISHED (rc=$rc)"
log "Scores: grep -h OVERALL $EXP_ROOT/SC_LibriSpeech_2spk_2500h_story_*/models_finetune*/*/dscore_*.log"
exit $rc
